
[mlflow.client]
experiment_name = "GraphCG"

[mlflow.server]
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 300
enable_checkpointing = true
gradient_clip_value = 2
#fast_dev_run = true

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions_latent"]

[[trainer.callbacks]]
name = "ModelCheckpoint"
dirpath = "@format {this.paths.output_dir}"
filename = "ffnn"
monitor = "val_loss"
save_top_k = 1
save_weights_only = true
every_n_epoch = 50
enable_version_counter = false

[model]
name = "ConstantWidthFFNN"
module_path = "dlkit.nn.ffnn"
hidden_size = 50
num_layers = 6
#dropout = 0.1

[model.loss_function]
name = "mse_loss"
module_path = "torch.nn.functional"

[model.optimizer]
name = "RAdam"
lr = 5e-2

[model.scheduler]
name = "ReduceLROnPlateau"
factor = 0.5
patience = 20
min_lr = 1e-6

[[model.feature_transforms]]
name = "MinMaxScaler"

[[model.metrics]]
name = "MeanAbsolutePercentageError"


[datamodule]
name = "GraphDataModule"
val_size = 0.15
test_size = 0.15
#idx_split = "@format {this.paths.input_dir}\\idx_split.json"

[dataset]
name = "GraphDataset"
root = "@format {this.paths.root}"

features = "@format {this.paths.input_dir}\\rhs.npy"
targets = "@format {this.paths.input_dir}\\solution.npy"
edge_index = "@format {this.paths.input_dir}\\matrix.npy"

[dataloader]
num_workers = 5
batch_size = 256
persistent_workers = true
pin_memory = true

[paths]
root = "M:\\shared\\graph-cg"
input_dir = "@format {this.paths.root}\\raw"
output_dir = "@format {this.paths.root}"
mlruns_dir = "M:\\constantinos\\data\\dynamic\\mlruns"

[optuna]
n_trials = 200

[optuna.model]
module_path = "dlkit.networks.ffnn"
hidden_size = {low=5, high=1000, step= 100}
num_layers = {low=1, high=8, step=1}
normalize = {choices=["none", "layer", "batch"]}
drop = {low=0, high=0.5, step=0.1}
