[project]
name = "experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlkit>=0.1.0",
    "pytorch-forecasting>=1.3.0",
]

[tool.uv.sources]
dlkit = { path = "../dlkit", editable = true }

[tool.ruff.lint]
extend-select = [
    "UP", # pyupgrade
    "D", # pydocstyle
]

[tool.ruff.lint.pydocstyle]
convention = "google"
