[project]
name = "experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "dlkit>=0.1.0",
    "seaborn>=0.13.2",
    "tcl>=0.2",
    "torch-geometric>=2.6.1",
]

[tool.uv.sources]
dlkit = { path = "../dlkit", editable = true }

[tool.ruff.lint]
extend-select = [
    "UP", # pyupgrade
    "D", # pydocstyle
]

[tool.ruff.lint.pydocstyle]
convention = "google"
