id = "gaussian-cg50-45x15randomE"

[source]
matrix_path = "${NEURALLS_RAW_DIR}/SpectralData/45x15randomE/stiffness/*_subdomain_1_Kaa.txt"
enumerate_by = "name"
parameters_paths = [
  "${NEURALLS_RAW_DIR}/SpectralData/45x15randomE/stiffness/*_YoungModuli_E1_E2_E3_E4.txt",
]

[generation]
normalize = "matrix"
shuffle = true
seed = 42

[[generation.strategy]]
name = "gaussian_residuals"
samples = 10000
cg_iters = 50

[output]
data_dir = "${NEURALLS_PROCESSED_DIR}"
