id = "solutions-cg1-45x15randomE"

[source]
matrix_path = "${NEURALLS_RAW_DIR}/SpectralData/45x15randomE/stiffness/*_subdomain_1_Kaa.txt"
enumerate_by = "name"
solutions_path = "${NEURALLS_RAW_DIR}/SpectralData/45x15-displacements/UaVectorsFromSpectral/ua_vector from_spectral_no_realization_*.txt"
parameters_paths = [
  "${NEURALLS_RAW_DIR}/SpectralData/45x15randomE/stiffness/*_YoungModuli_E1_E2_E3_E4.txt",
]

[generation]
normalize = "matrix"
shuffle = true
seed = 42

[[generation.strategy]]
name = "solution_archive"
samples = -1
solutions_glob = "${NEURALLS_RAW_DIR}/SpectralData/45x15-displacements/UaVectorsFromSpectral/ua_vector from_spectral_no_realization_*.txt"

[output]
data_dir = "${NEURALLS_PROCESSED_DIR}"
