[run]
type = "train"
seed = 42
precision = "64"
model = "../../profiles/model/ffnn/scale-eq-const/silu-6L-b.toml"
data = "../../profiles/data/array-small-batch.toml"
training = "../../profiles/training/conservative-plateau.toml"
plots = "../../profiles/plots/default.toml"
