[run]
name = "E=22E6, ω=5, dt=0.01, KLterms=1"
mode = "mlflow"

[mlflow.client]
experiment_name = "@format FFNN({this.run.name})"

[mlflow.server]
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 500
enable_checkpointing = true
gradient_clip_value = 2
#fast_dev_run = true

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions_latent"]

[[trainer.callbacks]]
name = "ModelCheckpoint"
dirpath = "@format {this.paths.output_dir}"
filename = "ffnn"
monitor = "val_loss"
save_top_k = 1
save_weights_only = true
every_n_epoch = 50
enable_version_counter = false

[model]
name = "ConstantWidthFFNN"
module_path = "dlkit.nn.ffnn"
hidden_size = 50
num_layers = 6
#dropout = 0.1


[model.optimizer]
name = "RAdam"
lr = 1e-3

[model.scheduler]
name = "ReduceLROnPlateau"
factor = 0.5
patience = 50
min_lr = 1e-6

[[model.feature_transforms]]
name = "MinMaxScaler"

[[model.metrics]]
name = "MeanAbsolutePercentageError"


[datamodule]
val_size = 0.15
test_size = 0.15

[dataset]
name = "NumpyDataset"

[dataloader]
num_workers = 5
batch_size = 256
persistent_workers = true
pin_memory = true

[paths]
root = "M:\\shared\\Serafeim_Atzarakis\\results\\CantileverDynamicLinear\\"
input_dir = "@format {this.paths.root}\\python_experimenting\\{this.run.name}"
output_dir = "@format {this.paths.root}"
mlruns_dir = "M:\\constantinos\\data\\dynamic\\mlruns"
predictions_dir = "@format {this.paths.output_dir}"
features = "@format {this.paths.input_dir}\\train_model_params.npy"
targets = "@format {this.paths.output_dir}\\latent.npy"
predictions = "@format {this.paths.predictions_dir}\\predictions_latent.npy"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
checkpoint = "@format {this.paths.output_dir}\\ffnn.ckpt"

[optuna]
n_trials = 200

[optuna.model]
module_path = "dlkit.networks.ffnn"
hidden_size = {low=5, high=1000, step= 100}
num_layers = {low=1, high=8, step=1}
normalize = {choices=["none", "layer", "batch"]}
drop = {low=0, high=0.5, step=0.1}
