[run]
type = "train"
seed = 42
precision = "64"
model = "../../profiles/model/ffnn/scale-equivariant-constant-width-factorized.toml"
data = "../../profiles/data/array-default.toml"
training = "../../profiles/training/extended.toml"
plots = "../../profiles/plots/default.toml"
