[run]
type = "train"
seed = 42
precision = "64"
model = "../../profiles/model/ffnn/scale-equivariant-embedded-fully-factorized.toml"
data = "../../profiles/data/array-default.toml"
training = "../../profiles/training/limited-200.toml"
