mlflow.enable = true
[mlflow.client]
experiment_name = "TFT"

[mlflow.server]
host = "localhost"
port = 35382
backend_store_uri = "@format sqlite:///{this.paths.output_dir}/mlruns/tft/mlflow.db"
artifacts_destination = "@format file:///{this.paths.output_dir}/mlruns/tft/artifacts"
terminate_apps_on_port = true

[trainer]
max_epochs = 300
gradient_clip_val = 5
#fast_dev_run = true
enable_checkpointing = true

[[trainer.callbacks]]
name = "ModelCheckpoint"
filename = "tft"
monitor = "val_loss"
mode = "min"
save_top_k = 1
save_last = true
every_n_epoch = 10
enable_version_counter = false
dirpath = "@format {this.paths.output_dir}\\checkpoints"

[model]
name = "TemporalFusionTransformer"
module_path = "pytorch_forecasting"
hidden_size = 7
lstm_layers = 2
attention_head_size = 1
log_interval = 5
predict = false
learning_rate = 1e-7


[datamodule]
name = "TimeSeriesDataModule"
test_size = 0.15
validation_size = 0.15


[dataset]
name = "ForecastingDataset"
time_idx = "step"
max_encoder_length = 30
prediction_length = 1
target = "pc_0"
time_varying_unknown_reals = ["pc_0", "pc_1", "pc_2"]
time_varying_known_reals = ["time"]
static_reals = ["param_0", "param_1", "param_2"]
group_ids = ["sample"]

[dataloader]
num_workers = 30
batch_size = 1000
persistent_workers = true
pin_memory = true

[paths]
root = "M:\\constantinos\\data\\bio\\5-equations"
input_dir = "M:\\constantinos\\data\\bio\\5-equations\\input"
output_dir = "@format {this.paths.root}\\output"
features = "@format {this.paths.input_dir}\\pca.parquet"
parameters = "@format {this.paths.input_dir}\\parameters.npy"
time = "@format {this.paths.input_dir}\\timeStepTotalTimes.txt"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
