[run]
type = "search"
seed = 42
precision = "64"
data = "../../profiles/data/array-small-batch.toml"
training = "../../profiles/training/conservative-plateau.toml"
plots = "../../profiles/plots/default.toml"


[model]
name = "ScaleEquivariantEmbeddedFactorizedFFNN"
project = false
activation = "silu"
dropout = 0.0
norm = "l2"
num_layers = 6
bias = true

[search]
objective = "val/loss"
n_trials = 100

[search.space]
"model.project" = { type = "categorical", choices = [true, false] }
"model.num_layers" = { type = "int", low = 1, high = 6 }
"model.activation" = { type = "categorical", choices = ["relu", "gelu", "silu", "tanh", "sigmoid", "leaky_relu", "identity"] }
"model.bias" = { type = "categorical", choices = [true, false] }
"model.dropout" = { type = "float", low = 0.0, high = 0.5 }
