[run]
type = "train"
seed = 42
precision = "64"
data = "../../profiles/data/array-default.toml"
training = "../../profiles/training/extended-conservative-plateau.toml"
plots = "../../profiles/plots/default.toml"

[model]
name = "ScaleEquivariantEmbeddedFactorizedFFNN"
num_layers = 3
activation = "relu"
bias = false
dropout = 0.0
