[training.trainer]
max_epochs = 500
accelerator = "auto"
enable_checkpointing = false
overfit_batches = 1

[training.optimizer.default_optimizer]
name = "AdamW"

[training.optimizer.default_scheduler]
name = "ReduceLROnPlateau"
monitor = "train/loss"
mode = "min"
factor = 0.5
patience = 10
cooldown = 5
threshold = 0.001
min_lr = 1e-06

[training.loss]
name = "relative_vector_norm_loss"
module_path = "dlkit.domain.losses"
target_key = "targets.y"

[[training.metrics]]
name = "RelativeVectorNormError"
module_path = "dlkit.domain.metrics"
norm_ord = 2
vector_dim = -1
