[run]
type = "train"
seed = 42
precision = "64"
data = "../../profiles/data/deeponet-branch-trunk.toml"
training = "../../profiles/training/extended-conservative-plateau.toml"
plots = "../../profiles/plots/default.toml"

[model]
name = "HyperDeepONet"
basis_dim = 8
branch_hidden_size = 256
branch_num_layers = 4
branch_num_lanes = 2
trunk_hidden_size = 64
trunk_num_layers = 4
trunk_num_lanes = 2
activation = "gelu"
normalize = "layer"
bias = false
dropout = 0.0
