[optuna]
enable = true
n_trials = 150


[mlflow]
enable = true

[mlflow.client]
experiment_name = "P-CAE-Optuna"

[mlflow.server]
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 500
enable_checkpointing = true

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions", "predictions_latent"]

[[trainer.callbacks]]
name = "ModelCheckpoint"
dirpath = "@format {this.paths.checkpoint_dir}"
filename = "cae"
save_top_k = 1
save_weights_only = true
every_n_epoch = 10
enable_version_counter = false

[model]
name = "cae.SkipCAE1d"
num_layers = {low=1, high=6, step=1}
latent_size = {low =3, high=9, step=1}
kernel_size  = {low=3, high=15, step=2}
latent_channels = {low=10, high=1000, step=50}
latent_width = {low=10, high=600, step=50}
is_autoencoder = true
predict = false

[model.optimizer]
name = "RAdam"
lr = 1e-3

[model.scheduler]
name = "ReduceLROnPlateau"
factor = 0.5
patience = 15
min_lr = 1e-6

[[model.feature_transforms]]
name = "MinMaxScaler"
dim = [0, -1]

[model.train_loss]
name = "mean_squared_error"

[[model.metrics]]
name = "MeanAbsolutePercentageError"


[datamodule]
val_size = 0.15
test_size = 0.15

[dataset]
name = "NumpyDataset"

[dataloader]
num_workers = 5
batch_size = 128
persistent_workers = true
pin_memory = true

[paths]
root = "M:\\constantinos\\data\\bio\\5-equations"
input_dir = "M:\\constantinos\\data\\bio\\5-equations\\input"
features = "@format {this.paths.input_dir}\\p.npy"
output_dir = "@format {this.paths.root}\\output"
predictions_dir = "@format {this.paths.output_dir}"
mlruns_dir = "@format {this.paths.output_dir}\\mlruns"
latent = "@format {this.paths.output_dir}\\predictions_latent.npy"
figures = "@format {this.paths.output_dir}\\figures\\"
parameters = "@format {this.paths.input_dir}\\parameters.npy"
predictions = "@format {this.paths.predictions_dir}\\p-predictions.npy"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
checkpoint_dir = "@format {this.paths.output_dir}\\checkpoints\\"
