[run]
name = "E=22E6, ω=5, dt=0.01, KLterms=1"
mode = "inference"

[mlflow]
enable = true
[mlflow.client]
experiment_name = "@format CAE({this.run.name})"

[mlflow.server]
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 500
enable_checkpointing = true
#grad_clip_norm = 0.01

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions", "latent"]

[[trainer.callbacks]]
name = "ModelCheckpoint"
dirpath = "@format {this.paths.output_dir}"
filename = "cae"
save_top_k = 1
save_weights_only = true
every_n_epoch = 10
enable_version_counter = false
monitor = "val_loss"

[model]
name = "cae.SkipCAE1d"
num_layers = 4
latent_size = 2
kernel_size  = 5
latent_channels = 400
latent_width = 20
#dropout = 0.1
is_autoencoder = true

[model.optimizer]
name = "RAdam"
lr = 5e-4

[model.scheduler]
name = "ReduceLROnPlateau"
factor = 0.5
patience = 30
min_lr = 1e-6

[[model.feature_transforms]]
name = "MinMaxScaler"
dim = [0, -1]

[[model.metrics]]
name = "MeanAbsolutePercentageError"

[datamodule]
val_size = 0.15
test_size = 0.15

[dataset]
name = "NumpyDataset"

[dataloader]
num_workers = 5
batch_size = 128
persistent_workers = true
pin_memory = true


[paths]
root = "M:\\shared\\Serafeim_Atzarakis\\results\\CantileverDynamicLinear"
mlruns_dir = "M:\\constantinos\\data\\dynamic\\mlruns"
input_dir = "@format {this.paths.root}\\python_experimenting\\{this.run.name}"
output_dir = "@format {this.paths.root}"
checkpoint = "@format {this.paths.output_dir}\\cae.ckpt"
predictions_dir = "@format {this.paths.output_dir}"
features = "@format {this.paths.input_dir}\\train_solutions.npy"
parameters = "@format {this.paths.input_dir}\\train_model_params.npy"
latent = "@format {this.paths.output_dir}\\latent.npy"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
