name = "E=22E6, ω=5, dt=0.01, KLterms=1"
[mlflow]
enable = true
[mlflow.client]
experiment_name = "@format CAE({this.name})"

[mlflow.server]
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 500
enable_checkpointing = true
#fast_dev_run = true

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions", "predictions_latent"]


[model]
name = "cae.SkipCAE1d"
num_layers = 3
latent_size = 3
kernel_size  = 9
latent_channels = 100
latent_width = 50
is_autoencoder = true
checkpoint = "@format {this.paths.output_dir}\\cae.ckpt"
train = false
test = false
predict = false


[[model.feature_transforms]]
name = "MinMaxScaler"
dim = [0, -1]



[datamodule]
val_size = 0.15
test_size = 0.15

[dataset]
name = "NumpyDataset"

[dataloader]
num_workers = 5
batch_size = 128
persistent_workers = true
pin_memory = true


[paths]
root = "M:\\shared\\Serafeim_Atzarakis\\results\\CantileverDynamicLinear"
mlruns_dir = "M:\\constantinos\\data\\dynamic\\mlruns"
input_dir = "@format {this.paths.root}\\python_experimenting\\{this.name}"
output_dir = "@format {this.paths.root}"
predictions_dir = "@format {this.paths.output_dir}"
features = "@format {this.paths.input_dir}\\train_solutions.npy"
parameters = "@format {this.paths.input_dir}\\train_model_params.npy"
latent = "@format {this.paths.output_dir}\\predictions_latent.npy"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
