[mlflow]
enable = true
[mlflow.client]
experiment_name = "cae"

[mlflow.server]
host = "localhost"
port = 10001
backend_store_uri = "@format sqlite:///{this.paths.mlruns_dir}/mlflow.db"
artifacts_destination = "@format file:///{this.paths.mlruns_dir}/artifacts"

[trainer]
max_epochs = 1000
enable_checkpointing = true
#fast_dev_run = true

[[trainer.callbacks]]
name = "NumpyWriter"
module_path = "dlkit.callbacks"
output_dir = "@format {this.paths.output_dir}"
filenames = ["predictions", "predictions_latent"]

[[trainer.callbacks]]
name = "ModelCheckpoint"
dirpath = "@format {this.paths.output_dir}"
filename = "cae"
save_top_k = 1
save_weights_only = true
every_n_epoch = 10
enable_version_counter = false

[model]
name = "cae.LinearCAE1d"
num_layers = {low=1, high=4}
latent_size = {low=6, high=12}
kernel_size  = {low=7, high=15, step=2}
latent_channels = {low=50, high=200, step=10}
latent_width = {low=30, high=100, step=10}
is_autoencoder = true
predict = false

[model.optimizer]
name = "RAdam"
lr = 0.001

[model.scheduler]
name = "ReduceLROnPlateau"
factor = 0.6
patience = 15
min_lr = 1e-6

[[model.feature_transforms]]
name = "MinMaxScaler"
dim = [0, -1]

[model.train_loss]
name = "mse_loss"
module_path = "torch.nn.functional"


[datamodule]
val_size = 0.15
test_size = 0.15

[dataset]
name = "NumpyDataset"

[dataloader]
num_workers = 5
batch_size = 128
persistent_workers = true
pin_memory = true

[optuna]
enable = true
n_trials = 150

[optuna.pruner]
name = "MedianPruner"
n_startup_trials=5
n_warmup_steps=30
interval_steps=10



[paths]
root = "M:\\shared\\Serafeim_Atzarakis\\results\\CantileverDynamicLinear"
mlruns_dir = "M:\\constantinos\\data\\dynamic\\mlruns"
input_dir = "@format {this.paths.root}"
output_dir = "@format {this.paths.root}"
predictions_dir = "@format {this.paths.output_dir}"
features = "@format {this.paths.input_dir}\\train_solutions.npy"
parameters = "@format {this.paths.input_dir}\\train_model_params.npy"
latent = "@format {this.paths.output_dir}\\predictions_latent.npy"
idx_split = "@format {this.paths.input_dir}\\idx_split.json"
