# Master registry for all FFNN experiments.

project_root = ".."
output_dir = "/data/projects/graph-cg/data/output"

[mlflow]
tracking_uri = "sqlite:////data/projects/graph-cg/data/output/mlruns/mlflow.db"

[names]
comparison = "Comparisons"

[[datasets]]
id = "solutions"
path = "datasets/solutions.toml"

[[datasets]]
id = "eigenvector-solutions-largest"
path = "datasets/eigenvector-solutions-largest.toml"

[[datasets]]
id = "eigenvector-solutions-smallest"
path = "datasets/eigenvector-solutions-smallest.toml"

[[datasets]]
id = "eigenvector-rhs-largest"
path = "datasets/eigenvector-rhs-largest.toml"

[[datasets]]
id = "eigenvector-rhs-smallest"
path = "datasets/eigenvector-rhs-smallest.toml"

[[models]]
id = "ffnn"
path = "models/ffnn.toml"

[[comparisons]]
id = "ffnn"
path = "comparison/ffnn.toml"

[[experiments]]
id = "ffnn_test_solutions"
dataset = "solutions"
model = "ffnn"

[[experiments]]
id = "ffnn_test_eigenvector_solutions_largest"
dataset = "eigenvector-solutions-largest"
model = "ffnn"

[[experiments]]
id = "ffnn_test_eigenvector_solutions_smallest"
dataset = "eigenvector-solutions-smallest"
model = "ffnn"

[[experiments]]
id = "ffnn_test_eigenvector_rhs_largest"
dataset = "eigenvector-rhs-largest"
model = "ffnn"

[[experiments]]
id = "ffnn_test_eigenvector_rhs_smallest"
dataset = "eigenvector-rhs-smallest"
model = "ffnn"
