# Master registry for datasets, models, comparisons, and experiments.

project_root = ".."
output_dir = "/data/projects/graph-cg/data/output"

[mlflow]
tracking_uri = "http://127.0.0.1:5000"

[names]
comparison = "Comparisons"

# -------
# Datasets
# -------

[[datasets]]
id = "solutions"
path = "datasets/solutions.toml"
display_name = "Solutions"

[[datasets]]
id = "residuals-100"
path = "datasets/residuals-100.toml"
display_name = "Solutions Residual 100"

[[datasets]]
id = "eig-rhs-largest"
path = "datasets/eig-rhs-largest.toml"
display_name = "Eig RHS Largest"

[[datasets]]
id = "eig-rhs-smallest"
path = "datasets/eig-rhs-smallest.toml"
display_name = "Eig RHS Smallest"

[[datasets]]
id = "eig-solutions-smallest"
path = "datasets/eig-solutions-smallest.toml"
display_name = "Eig Solutions Smallest"

[[datasets]]
id = "eig-solutions-largest"
path = "datasets/eig-solutions-largest.toml"
display_name = "Eig Solutions Largest"


[[datasets]]
id = "gaussian"
path = "datasets/gaussian-rhs.toml"
display_name = "gaussian-rhs"

[[datasets]]
id = "scaled-solutions"
path = "datasets/scaled-solutions.toml"
display_name = "Scaled Solutions"

[[datasets]]
id = "sparse-rhs"
path = "datasets/sparse-rhs.toml"
display_name = "Sparse RHS"

[[datasets]]
id = "eig-few-solutions-largest"
path = "datasets/eig-few-solutions-largest.toml"
display_name = "Eig Few Solutions Largest"

[[datasets]]
id = "eig-few-solutions-smallest"
path = "datasets/eig-few-solutions-smallest.toml"
display_name = "Eig Few Solutions Smallest"

[[datasets]]
id = "eig-few-rhs-largest"
path = "datasets/eig-few-rhs-largest.toml"
display_name = "Eig Few RHS Largest"

[[datasets]]
id = "eig-few-rhs-smallest"
path = "datasets/eig-few-rhs-smallest.toml"
display_name = "Eig Few RHS Smallest"

# ------
# Models
# ------

[[models]]
id = "linear"
path = "models/linear.toml"
display_name = "NormScaledLinearFFNN"

[[models]]
id = "linear-l2"
path = "models/linear-l2.toml"
display_name = "NormScaledLinearFFNN L2"

# -----------
# Experiments
# -----------

# [[experiments]]
# id = "solutions"
# dataset = "solutions"
# model = "linear-l2"
# display_name = "Solutions"

[[experiments]]
id = "spectral-energy"
dataset = "solutions"
model = "linear"
display_name = "Solutions L-notay"

# [[experiments]]
# id = "eig-rhs-largest"
# dataset = "eig-rhs-largest"
# model = "linear"
# display_name = "Eig RHS Largest"

# [[experiments]]
# id = "eig-rhs-smallest"
# dataset = "eig-rhs-smallest"
# model = "linear"
# display_name = "Eig RHS Smallest"

# [[experiments]]
# id = "eig-solutions-largest"
# dataset = "eig-solutions-largest"
# model = "linear"
# display_name = "Eig Sol Largest"

# [[experiments]]
# id = "eig-solutions-smallest"
# dataset = "eig-solutions-smallest"
# model = "linear"
# display_name = "Eig Sol Smallest"

# [[experiments]]
# id = "residuals"
# dataset = "residuals-100"
# model = "linear"
# display_name = "Residuals"




# -----------
# Comparisons
# -----------

[[comparisons]]
id = "spectral"
path = "comparison/linear.toml"
display_name = "Spectral Comparison"

[[comparisons]]
id = "scaled-solutions"
path = "comparison/scaled-solutions.toml"
display_name = "Scaled Spectral Comparison"

[[comparisons]]
id = "sparse-rhs"
path = "comparison/sparse-rhs.toml"
display_name = "Sparse RHS Comparison"

[[comparisons]]
id = "eig-few-solutions-largest"
path = "comparison/eig-few-solutions-largest.toml"
display_name = "Eig Few Sol Largest Comparison"

[[comparisons]]
id = "eig-few-solutions-smallest"
path = "comparison/eig-few-solutions-smallest.toml"
display_name = "Eig Few Sol Smallest Comparison"

[[comparisons]]
id = "eig-few-rhs-largest"
path = "comparison/eig-few-rhs-largest.toml"
display_name = "Eig Few RHS Largest Comparison"

[[comparisons]]
id = "eig-few-rhs-smallest"
path = "comparison/eig-few-rhs-smallest.toml"
display_name = "Eig Few RHS Smallest Comparison"
