# This is the master configuration file.
# It lists the active experiments and their paths relative to this file.

project_root = ".."
defaults_dir = "experiments/default"
output_dir = "/data/projects/graph-cg/data/output"

[experiments]
ffnn_test_solutions = "experiments/ffnn_test_solutions"
ffnn_test_eigenvector_solutions_largest = "experiments/ffnn_test_eigenvector_solutions_largest"
ffnn_test_eigenvector_solutions_smallest = "experiments/ffnn_test_eigenvector_solutions_smallest"
ffnn_test_eigenvector_rhs_largest = "experiments/ffnn_test_eigenvector_rhs_largest"
ffnn_test_eigenvector_rhs_smallest = "experiments/ffnn_test_eigenvector_rhs_smallest"
