[mlflow]
tracking_uri = "http://localhost:5000"

[names]
training = "Train-45x15randomE-Factorized-Single-Matrix"
comparison = "Compare-45x15randomE-Factorized-Single-Matrix"

[comparison_defaults]
rtol = 1.0e-6
atol = 1.0e-14
max_iterations = 200
stopping_criterion = "residual_norm"
m_max = 20

[[comparison_defaults.preconditioners]]
name = "none"
type = "identity"

[[comparison_defaults.preconditioners]]
name = "jacobi"
type = "jacobi"

[[comparison_defaults.preconditioners]]
name = "ic0"
type = "ic0"

[[datasets]]
id = "gaussian-cg100-45x15randomE-single-matrix"
path = "../../datasets/train/45x15randomE/gaussian-cg100-single-matrix.toml"
display_name = "Gaussian CG-100 45x15randomE Single Matrix"

[[datasets]]
id = "scaled-solutions-45x15randomE-single-matrix"
path = "../../datasets/test/45x15randomE/scaled-solutions-single-matrix.toml"
display_name = "Scaled Solutions 45x15randomE Single Matrix"

[[datasets]]
id = "sparse-rhs-45x15randomE-single-matrix"
path = "../../datasets/test/45x15randomE/sparse-rhs-single-matrix.toml"
display_name = "Sparse RHS 45x15randomE Single Matrix"

[[models]]
id = "constant-width-factorized"
path = "../../models/ffnn/constant-width-factorized.toml"
display_name = "Constant-Width Factorized FFNN"

[[models]]
id = "constant-width-simple-factorized"
path = "../../models/ffnn/constant-width-simple-factorized.toml"
display_name = "Constant-Width Simple Factorized FFNN"

[[models]]
id = "scale-equivariant-constant-width-factorized"
path = "../../models/ffnn/scale-equivariant-constant-width-factorized.toml"
display_name = "Scale-Equivariant Constant-Width Factorized FFNN"

[[models]]
id = "scale-equivariant-constant-width-simple-factorized"
path = "../../models/ffnn/scale-equivariant-constant-width-simple-factorized.toml"
display_name = "Scale-Equivariant Constant-Width Simple Factorized FFNN"

[[comparisons]]
id = "gaussian-cg100-single-matrix"
matrix_dataset = "gaussian-cg100-45x15randomE-single-matrix"
rhs_dataset = "gaussian-cg100-45x15randomE-single-matrix"
experiments = [
  "constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
]

[[comparisons]]
id = "scaled"
matrix_dataset = "gaussian-cg100-45x15randomE-single-matrix"
rhs_dataset = "scaled-solutions-45x15randomE-single-matrix"
experiments = [
  "constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
]

[[comparisons]]
id = "sparse"
matrix_dataset = "gaussian-cg100-45x15randomE-single-matrix"
rhs_dataset = "sparse-rhs-45x15randomE-single-matrix"
experiments = [
  "constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-factorized-gaussian-cg100-45x15randomE-single-matrix",
  "scale-equivariant-constant-width-simple-factorized-gaussian-cg100-45x15randomE-single-matrix",
]

[[experiments]]
dataset = "gaussian-cg100-45x15randomE-single-matrix"
model = "constant-width-factorized"

[[experiments]]
dataset = "gaussian-cg100-45x15randomE-single-matrix"
model = "constant-width-simple-factorized"

[[experiments]]
dataset = "gaussian-cg100-45x15randomE-single-matrix"
model = "scale-equivariant-constant-width-factorized"

[[experiments]]
dataset = "gaussian-cg100-45x15randomE-single-matrix"
model = "scale-equivariant-constant-width-simple-factorized"
