[mlflow]
tracking_uri = "http://localhost:5000"

[names]
training   = "Train-45x15randomE-Conditional-FiLMs"
comparison = "Compare-45x15randomE-Conditional-FiLMs"

[comparison_defaults]
rtol               = 1.0e-6
atol               = 1.0e-14
max_iterations     = 200
stopping_criterion = "residual_norm"
m_max              = 20

[[comparison_defaults.preconditioners]]
name = "none"
type = "identity"

[[comparison_defaults.preconditioners]]
name = "jacobi"
type = "jacobi"

[[comparison_defaults.preconditioners]]
name = "ic0"
type = "ic0"

[[datasets]]
id           = "gaussian-cg1-45x15randomE"
path         = "../../datasets/train/45x15randomE/gaussian-cg1.toml"
display_name = "Gaussian CG-1 45x15randomE"

[[datasets]]
id           = "gaussian-cg10-45x15randomE"
path         = "../../datasets/train/45x15randomE/gaussian-cg10.toml"
display_name = "Gaussian CG-10 45x15randomE"

[[datasets]]
id           = "gaussian-cg50-45x15randomE"
path         = "../../datasets/train/45x15randomE/gaussian-cg50.toml"
display_name = "Gaussian CG-50 45x15randomE"

[[datasets]]
id           = "gaussian-cg100-45x15randomE"
path         = "../../datasets/train/45x15randomE/gaussian-cg100.toml"
display_name = "Gaussian CG-100 45x15randomE"

[[models]]
id           = "film-ffnn"
path         = "../../models/film/film-ffnn.toml"
display_name = "FiLM FFNN"

[[models]]
id           = "film-ffnn-embedded"
path         = "../../models/film/film-ffnn-embedded.toml"
display_name = "FiLM Embedded FFNN"

[[comparisons]]
id             = "gaussian-cg1"
matrix_dataset = "gaussian-cg1-45x15randomE"
rhs_dataset    = "gaussian-cg1-45x15randomE"
experiments    = [
  "film-ffnn-gaussian-cg1-45x15randomE",
  "film-ffnn-embedded-gaussian-cg1-45x15randomE",
]

[[comparisons]]
id             = "gaussian-cg10"
matrix_dataset = "gaussian-cg10-45x15randomE"
rhs_dataset    = "gaussian-cg10-45x15randomE"
experiments    = [
  "film-ffnn-gaussian-cg10-45x15randomE",
  "film-ffnn-embedded-gaussian-cg10-45x15randomE",
]

[[comparisons]]
id             = "gaussian-cg50"
matrix_dataset = "gaussian-cg50-45x15randomE"
rhs_dataset    = "gaussian-cg50-45x15randomE"
experiments    = [
  "film-ffnn-gaussian-cg50-45x15randomE",
  "film-ffnn-embedded-gaussian-cg50-45x15randomE",
]

[[comparisons]]
id             = "gaussian-cg100"
matrix_dataset = "gaussian-cg100-45x15randomE"
rhs_dataset    = "gaussian-cg100-45x15randomE"
experiments    = [
  "film-ffnn-gaussian-cg100-45x15randomE",
  "film-ffnn-embedded-gaussian-cg100-45x15randomE",
]

[[experiments]]
dataset = "gaussian-cg1-45x15randomE"
model   = "film-ffnn"

[[experiments]]
dataset = "gaussian-cg1-45x15randomE"
model   = "film-ffnn-embedded"

[[experiments]]
dataset = "gaussian-cg10-45x15randomE"
model   = "film-ffnn"

[[experiments]]
dataset = "gaussian-cg10-45x15randomE"
model   = "film-ffnn-embedded"

[[experiments]]
dataset = "gaussian-cg50-45x15randomE"
model   = "film-ffnn"

[[experiments]]
dataset = "gaussian-cg50-45x15randomE"
model   = "film-ffnn-embedded"

[[experiments]]
dataset = "gaussian-cg100-45x15randomE"
model   = "film-ffnn"

[[experiments]]
dataset = "gaussian-cg100-45x15randomE"
model   = "film-ffnn-embedded"
