
[general]

[general.params]
rtol = 1.0e-6
atol = 1.0e-14
max_iterations = 200
stopping_criterion = "residual_norm"
m_max = 20

[general.data]
matrix_path = "${GRAPH_CG_PROCESSED_DIR}/solutions"
rhs_path = "${GRAPH_CG_PROCESSED_DIR}/gaussian-rhs"
# rhs_index = 0   # Which RHS sample to use (0 = first)

[[preconditioners]]
name = "none"
type = "identity"

[[preconditioners]]
name = "jacobi"
type = "jacobi"

[[preconditioners]]
name = "ic0"
type = "ic0"
