[mlflow]
tracking_uri = "http://localhost:5000"

[names]
training = "Overfit-45x15-Scale-Equivariant-CG"

[[datasets]]
id = "gaussian-cg50-45x15"
path = "../../datasets/train/45x15/gaussian-cg50.toml"
display_name = "Gaussian CG-50 45x15"

[[jobs]]
id = "scale-equivariant-constant-width-factorized"
path = "../../jobs/45x15/scale-equivariant-constant-width-factorized-overfit.toml"
display_name = "Scale Equivariant Constant Width FFNN"

[[jobs]]
id = "scale-equivariant-constant-width-factorized-relu"
path = "../../jobs/45x15/scale-equivariant-constant-width-factorized-relu-overfit.toml"
display_name = "Scale Equivariant Constant Width FFNN (ReLU)"

[[jobs]]
id = "scale-equivariant-embedded-factorized"
path = "../../jobs/45x15/scale-equivariant-embedded-factorized-overfit.toml"
display_name = "Scale Equivariant Embedded FFNN (GELU, bias)"

[[assignments]]
dataset = "gaussian-cg50-45x15"
job = "scale-equivariant-constant-width-factorized"

[[assignments]]
dataset = "gaussian-cg50-45x15"
job = "scale-equivariant-constant-width-factorized-relu"

[[assignments]]
dataset = "gaussian-cg50-45x15"
job = "scale-equivariant-embedded-factorized"
