[run]
type = "train"
seed = 42
precision = "64"
model = "../../profiles/model/deeponet/embedded-deeponet.toml"
data = "../../profiles/data/deeponet-branch-trunk.toml"
training = "../../profiles/training/default.toml"
